#!/usr/bin/env php
<?php

$config = require './config/config.php';
help($argv);

$author = $config['author'] ? : '';
$arg = explode('::', $argv[1]);
$type = ucfirst($arg[0]);
$name = ucfirst($arg[1]);
$option = isset($argv[2]) ? str_split($argv[2]) : [];
$tableName = isset($argv[3]) ? $argv[3] : '';

switch ($type) {
    //生成controller
    case 'Controller':
        $phpFile = $config[$type] . $name . 'Controller.php';                   //文件路径
        rewrite($phpFile, $option);                                             //是否重写
        $tableSql = getSql($argv[3]);
        preg_match_all('/`(\w+)` (\w+)\((\d+)\)(.*COMMENT [\'"](.+)[\'"])?/', $tableSql, $column);
        $keys = $column[1];                                                     //表字段
        $type = $column[2];                                                     //字段类型
        foreach ($type as $tkey => $val) {
            $type[$tkey] = strpos($val,'int') !== false ? 'int' : 'string';     //字段类型处理 目前非int则string
        }
        $length = $column[3];                                                   //字段长度
        $comment = $column[5];                                                  //字段说明
        $file = fopen('./template/Controller.txt', "r");
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            if (strpos($line, '{{validate}}') > -1) {
                foreach ($keys as $key => $val) {                               //处理校验规则
                    $lengthMsg = ($type[$key] == 'string' ? sprintf('length:[0,%s]', $length[$key]) : "min:0");
                    $temp = str_pad("                '$val'=>'sometime|$type[$key]|$lengthMsg',", 100);
                    if (!empty($comment[$key])) {                               //添加字段注释
                        $temp = $temp . '//' . $comment[$key] . PHP_EOL;
                    } else {
                        $temp = $temp . PHP_EOL;
                    }
                    file_put_contents($phpFile, $temp, FILE_APPEND);            //写文件
                }
            } else {
                $line = preg_replace('/{{date}}/', date('Y-m-d'), $line);       //日期处理
                $line = preg_replace('/{{key}}/', $name, $line);                //业务模块名称处理
                $line = preg_replace('/{{author}}/', $author, $line);           //作者信息
                file_put_contents($phpFile, $line, FILE_APPEND);                //写文件
            }
        }
        fclose($file);                                                          //关闭文件
        echo 'success, file path:' . $phpFile;                                  //成功信息输出
        break;
    //生成module
    case 'Module':
        $phpFile = $config[$type] . $name . '.php';
        rewrite($phpFile, $option);                                             //是否重写
        $file = fopen('./template/Module.txt', "r");
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            $line = preg_replace('/{{date}}/', date('Y-m-d'), $line);
            $line = preg_replace('/{{key}}/', $name, $line);
            $line = preg_replace('/{{author}}/', $author, $line);               //作者信息
            file_put_contents($phpFile, $line, FILE_APPEND);                    //文件追加
        }
        fclose($file);
        echo 'success, file path:' . $phpFile;
        break;
    //生成model
    case 'Model':
        $phpFile = $config[$type] . $name . 'Model.php';
        rewrite($phpFile, $option);

        $tableSql = getSql($argv[3]);
        preg_match_all('/`(\w+)` \w+/', $tableSql, $column);
        $column = $column[1];                                                   //表字段
        $file = fopen('./template/Model.txt', "r");
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            if (strpos($line, '{{column}}') > -1) {
               foreach ($column as $val) {
                   $temp = "        '$val'," . PHP_EOL;
                   file_put_contents($phpFile, $temp, FILE_APPEND);             //文件追加
               }
            } else {
                $line = preg_replace('/{{table}}/',$argv[3] , $line);
                $line = preg_replace('/{{key}}/', $name, $line);
                file_put_contents($phpFile, $line, FILE_APPEND);                //文件追加
            }

        }
        fclose($file);
        echo 'success, file path:' . $phpFile;
        break;
    //生成model
    case 'Tpl':
        $phpFile = $config[$type] . $name . '.php';
        rewrite($phpFile, $option);

        $tableSql = getSql($argv[3]);
        preg_match_all('/`(\w+)` (\w+)\((\d+)\)(.*COMMENT [\'"](.+)[\'"])?/', $tableSql, $column);
        $keys = $column[1];                                                     //表字段
        $type = $column[2];                                                     //字段类型
        foreach ($type as $tkey => $val) {
            if (strpos(strtolower($val),'tinyint') !== false) {
                $type[$tkey] = 'tinyint';                                       //字段类型处理 目前非int则string
            } else {
                $type[$tkey] = strpos($val,'int') !== false ? 'int' : 'string';     //字段类型处理 目前非int则string
            }
        }
        $length = $column[3];                                                   //字段长度
        $comment = $column[5];                                                  //字段说明
        $file = fopen('./template/Tpl.txt', "r");
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            if (strpos($line, '{{column}}') > -1) {
                foreach ($keys as $val) {
                    $temp = "        '$val'," . PHP_EOL;
                    file_put_contents($phpFile, $temp, FILE_APPEND);             //文件追加
                }
            } elseif (strpos($line, '{{tpl}}') > -1) {
                foreach ($keys as $key => $val) {                               //处理校验规则
                    $temp = '';
                    $temp .= "        '$val' => [" . PHP_EOL;
                    $temp .= "            'key' => '$val'," . PHP_EOL;
                    if ($type[$key] == 'tinyint') {
                        preg_match_all('/(.+)\[.*/', $comment[$key], $columnSub);
                        $columnSub = empty($columnSub[1][0]) ? trim($comment[$key]) : trim($columnSub[1][0]);        //枚举类型 注释说明 实例：数据状态[1:正常 0:失效]
                        $temp .= "            'name' => '$columnSub'," . PHP_EOL;
                    } else {
                        $temp .= "            'name' => '$comment[$key]'," . PHP_EOL;
                    }

                    if ($type[$key] == 'tinyint') {
                        $temp .= "            'type' => 'select'," . PHP_EOL;
                    } else {
                        $temp .= "            'type' => 'text'," . PHP_EOL;
                    }
                    $temp .= "            'require' => false," . PHP_EOL;
                    if (in_array($val, ['id', 'status', 'create_time', 'update_time'])) {
                        $temp .= "            'readonly' => true," . PHP_EOL;
                    } else {
                        $temp .= "            'readonly' => false," . PHP_EOL;
                    }
                    $temp .= "            'value' => ''," . PHP_EOL;
                    if ($type[$key] == 'tinyint') {
                        $temp .= "            'list' => []," . PHP_EOL;
                    }
                    $temp .= "        ]," . PHP_EOL;
                    file_put_contents($phpFile, $temp, FILE_APPEND);            //写文件
                }
            } elseif(strpos($line, '{{enum}}') > -1) {
                foreach ($keys as $key => $val) {                               //处理校验规则
                    if ($type[$key] == 'tinyint') {
                        preg_match_all('/.*\[(.*)\]/', $comment[$key], $columnEnum);
                        if (!empty($columnEnum[1][0])) {
                            preg_match_all('/([0-9]+[:：][^0-9]*) */', $columnEnum[1][0], $columnEnum);
                            if (!empty($columnEnum[1])) {
                                $temp = '';
                                $temp .= "        '$val' =>  [" . PHP_EOL;
                                foreach ($columnEnum[1] as $eVal) {
                                    $eVal = str_replace('：', ':', $eVal);
                                    $enumData = explode(':', $eVal);
                                    if (isset($enumData[0]) && isset($enumData[1])) {
                                        $enumData[1] = trim($enumData[1]);
                                        $enumData[0] = trim($enumData[0]);
                                        $temp .= "             $enumData[0] => '$enumData[1]'," . PHP_EOL;
                                    }
                                }
                                $temp .= "         ]," . PHP_EOL;
                                file_put_contents($phpFile, $temp, FILE_APPEND);            //写文件
                            }
                        }
                    }
                }
            } else {
                $line = preg_replace('/{{table}}/',$argv[3] , $line);
                $line = preg_replace('/{{key}}/', $name, $line);
                $line = preg_replace('/{{key-low}}/', strtolower($name), $line);
                file_put_contents($phpFile, $line, FILE_APPEND);                //文件追加
            }

        }
        fclose($file);
        echo 'success, file path:' . $phpFile;
        break;
    //生成ajax
    case 'Ajax':
        $phpFile = $config[$type] . $name . 'Controller.php';                   //文件路径
        rewrite($phpFile, $option);                                             //是否重写
        $tableSql = getSql($argv[3]);
        preg_match_all('/`(\w+)` (\w+)\((\d+)\)(.*COMMENT [\'"](.+)[\'"])?/', $tableSql, $column);
        $keys = $column[1];                                                     //表字段
        $type = $column[2];                                                     //字段类型
        foreach ($type as $tkey => $val) {
            $type[$tkey] = strpos($val,'int') !== false ? 'int' : 'string';     //字段类型处理 目前非int则string
        }
        $length = $column[3];                                                   //字段长度
        $comment = $column[5];                                                  //字段说明
        $file = fopen('./template/Ajax.txt', "r");
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            if (strpos($line, '{{validate}}') > -1) {
                foreach ($keys as $key => $val) {                               //处理校验规则
                    $lengthMsg = ($type[$key] == 'string' ? sprintf('length:[0,%s]', $length[$key]) : "min:0");
                    $temp = str_pad("                '$val'=>'sometime|$type[$key]|$lengthMsg',", 100);
                    if (!empty($comment[$key])) {                               //添加字段注释
                        $temp = $temp . '//' . $comment[$key] . PHP_EOL;
                    } else {
                        $temp = $temp . PHP_EOL;
                    }
                    file_put_contents($phpFile, $temp, FILE_APPEND);            //写文件
                }
            } else {
                $line = preg_replace('/{{date}}/', date('Y-m-d'), $line);       //日期处理
                $line = preg_replace('/{{key}}/', $name, $line);                //业务模块名称处理
                $line = preg_replace('/{{author}}/', $author, $line);           //作者信息
                file_put_contents($phpFile, $line, FILE_APPEND);                //写文件
            }
        }
        fclose($file);                                                          //关闭文件
        echo 'success, file path:' . $phpFile;                                  //成功信息输出
        break;

    case 'AjaxRoute':
        $phpFile = $config[$type];                                              //文件路径
        $file = fopen('./template/AjaxRoute.txt', "r");
        file_put_contents($phpFile, PHP_EOL, FILE_APPEND);                      //写文件
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            $line = preg_replace('/{{date}}/', date('Y-m-d'), $line);           //日期处理
            $line = preg_replace('/{{key}}/', $name, $line);                    //业务模块名称处理
            $line = preg_replace('/{{key-low}}/', lcfirst($name), $line);       //业务模块名称处理
            $line = preg_replace('/{{author}}/', $author, $line);               //作者信息
            file_put_contents($phpFile, $line, FILE_APPEND);                    //写文件
        }
        file_put_contents($phpFile, PHP_EOL, FILE_APPEND);                      //写文件
        fclose($file);                                                          //关闭文件
        echo 'success, file path:' . $phpFile;                                  //成功信息输出
        break;
    case 'PageRoute':
        $phpFile = $config[$type];                                              //文件路径
        $file = fopen('./template/PageRoute.txt', "r");
        file_put_contents($phpFile, PHP_EOL, FILE_APPEND);                      //写文件
        while(!feof($file))
        {
            $line = fgets($file);                                               //fgets()函数从文件指针中读取一行
            $line = preg_replace('/{{date}}/', date('Y-m-d'), $line);           //日期处理
            $line = preg_replace('/{{key}}/', $name, $line);                    //业务模块名称处理
            $line = preg_replace('/{{key-low}}/', lcfirst($name), $line);       //业务模块名称处理
            $line = preg_replace('/{{author}}/', $author, $line);               //作者信息
            file_put_contents($phpFile, $line, FILE_APPEND);                    //写文件
        }
        file_put_contents($phpFile, PHP_EOL, FILE_APPEND);                      //写文件
        fclose($file);                                                          //关闭文件
        echo 'success, file path:' . $phpFile;                                  //成功信息输出
        break;

}

//获取建表信息
function getSql($table, $configKey = 'jeanku')
{
    try {
        if (empty($config)) {
            $databases = require './config/database.php';
            $database = $databases[$configKey];
        }
        $dbh = new PDO(sprintf("mysql:host=%s;dbname=%s",$database['host'],$database['database']), $database['username'], $database['password']);
        $data = $dbh->query('set names \'UTF8\'');
        $data = $dbh->query('show create table ' . $table);
        foreach($data as $row) {
            $tableSql = $row[1];
        }
        $dbh = null;
        return $tableSql;
    } catch (PDOException $e) {
        print "Error!: " . $e->getMessage() . "<br/>";
        die();
    }
}

//是否重写文件
function rewrite($path, $option){
    if (file_exists($path)) {
        if (!in_array('r', $option)) {
            echo 'file already exist';
            exit;
        } else {
            file_put_contents($path, "");                        //文件重写 先清空
        }
    }
}

//获取帮组信息
function help($param){
    if ((isset($param[1]) && $param[1] == 'help') || empty($param[1])) {
        echo 'Usage:' . PHP_EOL;
        echo '    php artisan [type]::[name] [option] [parameter] ' . PHP_EOL;
        echo 'type::name:' . PHP_EOL;
        echo '    Controller  make Controller file' . PHP_EOL;
        echo '    Module      make module file' . PHP_EOL;
        echo '    Model       make model file' . PHP_EOL;
        echo '    Tpl         make tpl file' . PHP_EOL;
        echo '    Ajax        make ajax file' . PHP_EOL;
        echo '    AjaxRoute   make ajax route file' . PHP_EOL;
        echo 'option:' . PHP_EOL;
        echo '    -r        rewrite the file' . PHP_EOL;
        echo '    -t        [parameter] : table name' . PHP_EOL;
        echo 'demo:' . PHP_EOL;
        echo '    Controller  php artisan controller::menu -t t_manage_menu' . PHP_EOL;
        echo '    Module      php artisan module::menu' . PHP_EOL;
        echo '    Model       php artisan model::menu -t t_manage_menu' . PHP_EOL;
        echo '    Tpl         php artisan Tpl::menu -t t_manage_menu' . PHP_EOL;
        echo '    Ajax        php artisan Ajax::menu -t t_manage_menu' . PHP_EOL;
        echo '    AjaxRoute   php artisan AjaxRoute::menu' . PHP_EOL;
        echo '    PageRoute   php artisan PageRoute::menu' . PHP_EOL;
        echo 'file is exist:' . PHP_EOL;
        echo 'rewrite a existed file:' . PHP_EOL;
        echo '    Controller  php artisan model::menu -rt t_manage_menu' . PHP_EOL;
        exit;
    }
}
