#!/usr/bin/env php
<?php

//spl_autoload_register(function ($class) {
//    echo __DIR__ . '/app/' . str_replace('\\', __DIR__, substr($class, 3)) . '.php' .PHP_EOL;
//    exit;
//});

require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

require_once __DIR__ . '/app/Console3/Kernel.php';

$kernel = new App\Console\Kernel();

echo "<pre>";
print_r($kernel);
exit;

//$status = $kernel->handle(
//    $input = new Symfony\Component\Console\Input\ArgvInput,
//    new Symfony\Component\Console\Output\ConsoleOutput
//);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running. We will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/
//$kernel->terminate($input, $status);
//
//exit($status);
